### ISSUE TITLE
Demos for kubecon

### ISSUE THREAD

**Issue by slack** [deislabs/smi-spec#24]
Demo 1 **Traffic Routing**:
  * SMI TrafficSplit + flagger
  * Mesh support: Istio

Demo 2 **Traffic Policy**:
  * SMI Traffic* 
  * Mesh support: Consul Connect

Demo 3 **Billing (via Metrics)**:
  * SMI Metrics + kubecost (spinning an rps meter)
  * Mesh support: Linkerd

**Comment by surajssd** [comment]
@slack this issue can be closed?
