### ISSUE TITLE
weights should be whole numbers

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-spec#65]
Hey folks,

In the traffic split example yaml, there are instances where weights are strings with an ending `m` for milli and there are other instances where weights are just whole numbers like `1` or `0`. I was pretty confused when I first encountered the milli notation like many others and I couldn't find great documentation on how to use this. 

I understand now that `1 == 1000m` and that you'll want to take the sum of all weights in milli and then divide each service's weight by the sum to get the amount of traffic to send to a service. However, this is still pretty confusing to calculate when thinking about Istio for example. Istio doesn't use the milli notation. Weights are whole numbers where the weight must be 0-100 and the sum of the weights must be 100.

I'd like to see us standardize on what weights are and give better documentation here, so I have two points I'd like feedback on:
1. I'd like to propose that weights be whole numbers rather than strings. It will make weight calculation logic much easier.
2. I'd like for us to standardize on how we calculate weights so that a TrafficSplit resource means the same thing regardless of the service mesh implementation running under the hood. We can go the Istio route with percentage based weights if that makes sense. @grampelberg has a different point of view here to consider.

#62 converts all weight strings to whole numbers and adds the line to constrain weights whole numbers.

cc/ @nicholasjackson @lachie83 @grampelberg

**Comment by abonas** [comment]
related to #45 and I +1 the proposal here
