### ISSUE TITLE
how do we manage traffic split resources over time

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-spec#83]
How do people manager TrafficSplit resources over time? Do you just update the same TrafficSplit resource forever? Is there some pattern people have come up with that we could document?

**Comment by abonas** [comment]
Shouldn't traffic split vanish after some time? that is - deleted?
For example, for Canary or A/B testing, after the evaluation period, it will be determined whether the new version is good to go, and then the older one will be deleted/undeployed and then there won't be any need in traffic split afterwards?

**Comment by grampelberg** [comment]
It isn't harmful to keep it around, or delete it. From a complexity perspective, I'm 👍 to @abonas. Fewer things to reason about.

**Comment by michelleN** [comment]
Thanks! I see this is already mentioned in the [Workflow section of TrafficSplit](https://github.com/deislabs/smi-spec/blob/master/traffic-split.md#workflow) so I'll close this out. Cheers.
