### ISSUE TITLE
schedule TrafficPolicy and Identity call for next week

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-spec#98]

**Comment by bridgetkromhout** [comment]
Hi @grampelberg, let's talk about this at the next regularly scheduled call.

**Comment by grampelberg** [comment]
@bridgetkromhout awesome! Looking forward to it =)

**Comment by michelleN** [comment]
Chatted about it on the call and scheduled another in the smi slack so I'll close this out now. Thanks!
